### PR TITLE
Fix: display copy-pastable debug output.

### LINKED ISSUE #29: Make --debug copy-pastable
```
$ claude-swarm --debug
Starting Claude Swarm from claude-swarm.yml...
🐝 Starting Claude Swarm: Ruby Upgrade Swarm

📝 Session files will be saved to: /Users/dblock/.claude-swarm/sessions/Users+dblock+source+slack+swarm/20250621_105455/

✓ Generated MCP configurations in session directory

⚙️  Executing before commands...

Debug: Executing command 1/1: echo 'Getting started ...'
Command 1 output:
Getting started ...
Exit status: 0
✓ Before commands completed successfully

🚀 Launching main instance: lead_developer
   Model: opus
   Directory: /Users/dblock/source/slack
   Allowed tools: Bash

Running: ["claude", "--model", "opus", "--allowedTools", "Bash", "--append-system-prompt", "You are the lead developer coordinating the team.\nList all the directories in the current directory.\n", "--debug", "--mcp-config", "/Users/dblock/.claude-swarm/sessions/Users+dblock+source+slack+swarm/20250621_105455/lead_developer.mcp.json", "You are the lead developer coordinating the team.\nList all the directories in the current directory.\n\n\nNow just say 'I am ready to start'"]

```

It doesn't do anything and I don't know why. The problem is

```
~/source/slack/swarm$ claude "List current directories."
-bash: /opt/homebrew/bin/claude: No such file or directory
```

### PR DESCRIPTION
**Pull request by dblock**
Before:

```
Running: ["claude", "--model", "opus", "--allowedTools", "Bash,mcp__ruby_upgrader", "--append-system-prompt", "Find the Ruby projects in this directory.\nDo not recurse further than 3 levels deep.\nFor each project, identify the Ruby version used.\nPrint the project name next to the ruby version only.\nFor the first 5 projects with a Ruby version older than 3.5.5 use ruby_upgrader to upgrade the Ruby version.\n", "--debug", "--mcp-config", "/Users/dblock/.claude-swarm/sessions/Users+dblock+source+slack+swarm/20250622_084736/lead_developer.mcp.json", "Find the Ruby projects in this directory.\nDo not recurse further than 3 levels deep.\nFor each project, identify the Ruby version used.\nPrint the project name next to the ruby version only.\nFor the first 5 projects with a Ruby version older than 3.5.5 use ruby_upgrader to upgrade the Ruby version.\n\n\nNow just say 'I am ready to start'"]
```

After:

```
🏃 Running: claude --model opus --allowedTools Bash,mcp__ruby_upgrader --append-system-prompt 'Find the Ruby projects in this directory.
Do not recurse further than 3 levels deep.
For each project, identify the Ruby version used.
Print the project name next to the ruby version only.
For the first 5 projects with a Ruby version older than 3.5.5 use ruby_upgrader to upgrade the Ruby version.
' --debug --mcp-config /Users/dblock/.claude-swarm/sessions/Users+dblock+source+claude-swarm+dblock-claude-swarm/20250622_084813/lead_developer.mcp.json 'Find the Ruby projects in this directory.
Do not recurse further than 3 levels deep.
For each project, identify the Ruby version used.
Print the project name next to the ruby version only.
For the first 5 projects with a Ruby version older than 3.5.5 use ruby_upgrader to upgrade the Ruby version.


Now just say '\''I am ready to start'\'''
```

Closes #29

### CODE REVIEW

File: lib/claude_swarm.rb [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # frozen_string_literal: true
 
 # External dependencies
+require "time"
```
Comment (dblock) [inline lib/claude_swarm.rb:4]: I'm seeing this:

```
$ bundle exec ./exe/claude-swarm --debug ~/source/slack/swarm/claude-swarm.yml
Starting Claude Swarm from /Users/dblock/source/slack/swarm/claude-swarm.yml...
🐝 Starting Claude Swarm: Ruby Upgrade Swarm

📝 Session files will be saved to: /Users/dblock/.claude-swarm/sessions/Users+dblock+source+claude-swarm+dblock-claude-swarm/20250622_090430/

✓ Generated MCP configurations in session directory

Unexpected error: undefined method `iso8601' for an instance of Time
```

**Review by parruda — APPROVED** [review]
